/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamenesOficialesRouteImport } from './routes/examenes-oficiales'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemasIndexRouteImport } from './routes/temas.index'
import { Route as ExamenesIndexRouteImport } from './routes/examenes.index'
import { Route as EjercicioIdRouteImport } from './routes/ejercicio.$id'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as TemasSlugIndexRouteImport } from './routes/temas.$slug.index'
import { Route as ExamenesSlugIndexRouteImport } from './routes/examenes.$slug.index'
import { Route as AuthenticatedSimulacrosIndexRouteImport } from './routes/_authenticated/simulacros.index'
import { Route as TemasSlugSubtopicRouteImport } from './routes/temas.$slug.$subtopic'
import { Route as ExamenesSlugSimulacroRouteImport } from './routes/examenes.$slug.simulacro'
import { Route as AuthenticatedExamenIdRouteImport } from './routes/_authenticated/examen.$id'
import { Route as AuthenticatedExamenSesionSessionIdRouteImport } from './routes/_authenticated/examen-sesion.$sessionId'
import { Route as AuthenticatedAdminMateriasRouteImport } from './routes/_authenticated/admin/materias'
import { Route as AuthenticatedExamenSesionSessionIdIndexRouteImport } from './routes/_authenticated/examen-sesion.$sessionId.index'
import { Route as AuthenticatedAdminExamenesIndexRouteImport } from './routes/_authenticated/admin/examenes.index'
import { Route as AuthenticatedAdminEjerciciosIndexRouteImport } from './routes/_authenticated/admin/ejercicios.index'
import { Route as AuthenticatedExamenSesionSessionIdResultadoRouteImport } from './routes/_authenticated/examen-sesion.$sessionId.resultado'
import { Route as AuthenticatedAdminExamenesNuevoRouteImport } from './routes/_authenticated/admin/examenes.nuevo'
import { Route as AuthenticatedAdminExamenesIdRouteImport } from './routes/_authenticated/admin/examenes.$id'
import { Route as AuthenticatedAdminEjerciciosNuevoRouteImport } from './routes/_authenticated/admin/ejercicios.nuevo'
import { Route as AuthenticatedAdminEjerciciosIdRouteImport } from './routes/_authenticated/admin/ejercicios.$id'

const ExamenesOficialesRoute = ExamenesOficialesRouteImport.update({
  id: '/examenes-oficiales',
  path: '/examenes-oficiales',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasIndexRoute = TemasIndexRouteImport.update({
  id: '/temas/',
  path: '/temas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenesIndexRoute = ExamenesIndexRouteImport.update({
  id: '/examenes/',
  path: '/examenes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EjercicioIdRoute = EjercicioIdRouteImport.update({
  id: '/ejercicio/$id',
  path: '/ejercicio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TemasSlugIndexRoute = TemasSlugIndexRouteImport.update({
  id: '/temas/$slug/',
  path: '/temas/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenesSlugIndexRoute = ExamenesSlugIndexRouteImport.update({
  id: '/examenes/$slug/',
  path: '/examenes/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimulacrosIndexRoute =
  AuthenticatedSimulacrosIndexRouteImport.update({
    id: '/simulacros/',
    path: '/simulacros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TemasSlugSubtopicRoute = TemasSlugSubtopicRouteImport.update({
  id: '/temas/$slug/$subtopic',
  path: '/temas/$slug/$subtopic',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenesSlugSimulacroRoute = ExamenesSlugSimulacroRouteImport.update({
  id: '/examenes/$slug/simulacro',
  path: '/examenes/$slug/simulacro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExamenIdRoute = AuthenticatedExamenIdRouteImport.update({
  id: '/examen/$id',
  path: '/examen/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamenSesionSessionIdRoute =
  AuthenticatedExamenSesionSessionIdRouteImport.update({
    id: '/examen-sesion/$sessionId',
    path: '/examen-sesion/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMateriasRoute =
  AuthenticatedAdminMateriasRouteImport.update({
    id: '/materias',
    path: '/materias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedExamenSesionSessionIdIndexRoute =
  AuthenticatedExamenSesionSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExamenSesionSessionIdRoute,
  } as any)
const AuthenticatedAdminExamenesIndexRoute =
  AuthenticatedAdminExamenesIndexRouteImport.update({
    id: '/examenes/',
    path: '/examenes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEjerciciosIndexRoute =
  AuthenticatedAdminEjerciciosIndexRouteImport.update({
    id: '/ejercicios/',
    path: '/ejercicios/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedExamenSesionSessionIdResultadoRoute =
  AuthenticatedExamenSesionSessionIdResultadoRouteImport.update({
    id: '/resultado',
    path: '/resultado',
    getParentRoute: () => AuthenticatedExamenSesionSessionIdRoute,
  } as any)
const AuthenticatedAdminExamenesNuevoRoute =
  AuthenticatedAdminExamenesNuevoRouteImport.update({
    id: '/examenes/nuevo',
    path: '/examenes/nuevo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExamenesIdRoute =
  AuthenticatedAdminExamenesIdRouteImport.update({
    id: '/examenes/$id',
    path: '/examenes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEjerciciosNuevoRoute =
  AuthenticatedAdminEjerciciosNuevoRouteImport.update({
    id: '/ejercicios/nuevo',
    path: '/ejercicios/nuevo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEjerciciosIdRoute =
  AuthenticatedAdminEjerciciosIdRouteImport.update({
    id: '/ejercicios/$id',
    path: '/ejercicios/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/examenes-oficiales': typeof ExamenesOficialesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/panel': typeof AuthenticatedPanelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ejercicio/$id': typeof EjercicioIdRoute
  '/examenes/': typeof ExamenesIndexRoute
  '/temas/': typeof TemasIndexRoute
  '/admin/materias': typeof AuthenticatedAdminMateriasRoute
  '/examen-sesion/$sessionId': typeof AuthenticatedExamenSesionSessionIdRouteWithChildren
  '/examen/$id': typeof AuthenticatedExamenIdRoute
  '/examenes/$slug/simulacro': typeof ExamenesSlugSimulacroRoute
  '/temas/$slug/$subtopic': typeof TemasSlugSubtopicRoute
  '/simulacros/': typeof AuthenticatedSimulacrosIndexRoute
  '/examenes/$slug/': typeof ExamenesSlugIndexRoute
  '/temas/$slug/': typeof TemasSlugIndexRoute
  '/admin/ejercicios/$id': typeof AuthenticatedAdminEjerciciosIdRoute
  '/admin/ejercicios/nuevo': typeof AuthenticatedAdminEjerciciosNuevoRoute
  '/admin/examenes/$id': typeof AuthenticatedAdminExamenesIdRoute
  '/admin/examenes/nuevo': typeof AuthenticatedAdminExamenesNuevoRoute
  '/examen-sesion/$sessionId/resultado': typeof AuthenticatedExamenSesionSessionIdResultadoRoute
  '/admin/ejercicios/': typeof AuthenticatedAdminEjerciciosIndexRoute
  '/admin/examenes/': typeof AuthenticatedAdminExamenesIndexRoute
  '/examen-sesion/$sessionId/': typeof AuthenticatedExamenSesionSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/examenes-oficiales': typeof ExamenesOficialesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/panel': typeof AuthenticatedPanelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/ejercicio/$id': typeof EjercicioIdRoute
  '/examenes': typeof ExamenesIndexRoute
  '/temas': typeof TemasIndexRoute
  '/admin/materias': typeof AuthenticatedAdminMateriasRoute
  '/examen/$id': typeof AuthenticatedExamenIdRoute
  '/examenes/$slug/simulacro': typeof ExamenesSlugSimulacroRoute
  '/temas/$slug/$subtopic': typeof TemasSlugSubtopicRoute
  '/simulacros': typeof AuthenticatedSimulacrosIndexRoute
  '/examenes/$slug': typeof ExamenesSlugIndexRoute
  '/temas/$slug': typeof TemasSlugIndexRoute
  '/admin/ejercicios/$id': typeof AuthenticatedAdminEjerciciosIdRoute
  '/admin/ejercicios/nuevo': typeof AuthenticatedAdminEjerciciosNuevoRoute
  '/admin/examenes/$id': typeof AuthenticatedAdminExamenesIdRoute
  '/admin/examenes/nuevo': typeof AuthenticatedAdminExamenesNuevoRoute
  '/examen-sesion/$sessionId/resultado': typeof AuthenticatedExamenSesionSessionIdResultadoRoute
  '/admin/ejercicios': typeof AuthenticatedAdminEjerciciosIndexRoute
  '/admin/examenes': typeof AuthenticatedAdminExamenesIndexRoute
  '/examen-sesion/$sessionId': typeof AuthenticatedExamenSesionSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/examenes-oficiales': typeof ExamenesOficialesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/ejercicio/$id': typeof EjercicioIdRoute
  '/examenes/': typeof ExamenesIndexRoute
  '/temas/': typeof TemasIndexRoute
  '/_authenticated/admin/materias': typeof AuthenticatedAdminMateriasRoute
  '/_authenticated/examen-sesion/$sessionId': typeof AuthenticatedExamenSesionSessionIdRouteWithChildren
  '/_authenticated/examen/$id': typeof AuthenticatedExamenIdRoute
  '/examenes/$slug/simulacro': typeof ExamenesSlugSimulacroRoute
  '/temas/$slug/$subtopic': typeof TemasSlugSubtopicRoute
  '/_authenticated/simulacros/': typeof AuthenticatedSimulacrosIndexRoute
  '/examenes/$slug/': typeof ExamenesSlugIndexRoute
  '/temas/$slug/': typeof TemasSlugIndexRoute
  '/_authenticated/admin/ejercicios/$id': typeof AuthenticatedAdminEjerciciosIdRoute
  '/_authenticated/admin/ejercicios/nuevo': typeof AuthenticatedAdminEjerciciosNuevoRoute
  '/_authenticated/admin/examenes/$id': typeof AuthenticatedAdminExamenesIdRoute
  '/_authenticated/admin/examenes/nuevo': typeof AuthenticatedAdminExamenesNuevoRoute
  '/_authenticated/examen-sesion/$sessionId/resultado': typeof AuthenticatedExamenSesionSessionIdResultadoRoute
  '/_authenticated/admin/ejercicios/': typeof AuthenticatedAdminEjerciciosIndexRoute
  '/_authenticated/admin/examenes/': typeof AuthenticatedAdminExamenesIndexRoute
  '/_authenticated/examen-sesion/$sessionId/': typeof AuthenticatedExamenSesionSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/examenes-oficiales'
    | '/admin'
    | '/panel'
    | '/perfil'
    | '/ejercicio/$id'
    | '/examenes/'
    | '/temas/'
    | '/admin/materias'
    | '/examen-sesion/$sessionId'
    | '/examen/$id'
    | '/examenes/$slug/simulacro'
    | '/temas/$slug/$subtopic'
    | '/simulacros/'
    | '/examenes/$slug/'
    | '/temas/$slug/'
    | '/admin/ejercicios/$id'
    | '/admin/ejercicios/nuevo'
    | '/admin/examenes/$id'
    | '/admin/examenes/nuevo'
    | '/examen-sesion/$sessionId/resultado'
    | '/admin/ejercicios/'
    | '/admin/examenes/'
    | '/examen-sesion/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/examenes-oficiales'
    | '/admin'
    | '/panel'
    | '/perfil'
    | '/ejercicio/$id'
    | '/examenes'
    | '/temas'
    | '/admin/materias'
    | '/examen/$id'
    | '/examenes/$slug/simulacro'
    | '/temas/$slug/$subtopic'
    | '/simulacros'
    | '/examenes/$slug'
    | '/temas/$slug'
    | '/admin/ejercicios/$id'
    | '/admin/ejercicios/nuevo'
    | '/admin/examenes/$id'
    | '/admin/examenes/nuevo'
    | '/examen-sesion/$sessionId/resultado'
    | '/admin/ejercicios'
    | '/admin/examenes'
    | '/examen-sesion/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buscar'
    | '/examenes-oficiales'
    | '/_authenticated/admin'
    | '/_authenticated/panel'
    | '/_authenticated/perfil'
    | '/ejercicio/$id'
    | '/examenes/'
    | '/temas/'
    | '/_authenticated/admin/materias'
    | '/_authenticated/examen-sesion/$sessionId'
    | '/_authenticated/examen/$id'
    | '/examenes/$slug/simulacro'
    | '/temas/$slug/$subtopic'
    | '/_authenticated/simulacros/'
    | '/examenes/$slug/'
    | '/temas/$slug/'
    | '/_authenticated/admin/ejercicios/$id'
    | '/_authenticated/admin/ejercicios/nuevo'
    | '/_authenticated/admin/examenes/$id'
    | '/_authenticated/admin/examenes/nuevo'
    | '/_authenticated/examen-sesion/$sessionId/resultado'
    | '/_authenticated/admin/ejercicios/'
    | '/_authenticated/admin/examenes/'
    | '/_authenticated/examen-sesion/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  ExamenesOficialesRoute: typeof ExamenesOficialesRoute
  EjercicioIdRoute: typeof EjercicioIdRoute
  ExamenesIndexRoute: typeof ExamenesIndexRoute
  TemasIndexRoute: typeof TemasIndexRoute
  ExamenesSlugSimulacroRoute: typeof ExamenesSlugSimulacroRoute
  TemasSlugSubtopicRoute: typeof TemasSlugSubtopicRoute
  ExamenesSlugIndexRoute: typeof ExamenesSlugIndexRoute
  TemasSlugIndexRoute: typeof TemasSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/examenes-oficiales': {
      id: '/examenes-oficiales'
      path: '/examenes-oficiales'
      fullPath: '/examenes-oficiales'
      preLoaderRoute: typeof ExamenesOficialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas/': {
      id: '/temas/'
      path: '/temas'
      fullPath: '/temas/'
      preLoaderRoute: typeof TemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examenes/': {
      id: '/examenes/'
      path: '/examenes'
      fullPath: '/examenes/'
      preLoaderRoute: typeof ExamenesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejercicio/$id': {
      id: '/ejercicio/$id'
      path: '/ejercicio/$id'
      fullPath: '/ejercicio/$id'
      preLoaderRoute: typeof EjercicioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/temas/$slug/': {
      id: '/temas/$slug/'
      path: '/temas/$slug'
      fullPath: '/temas/$slug/'
      preLoaderRoute: typeof TemasSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examenes/$slug/': {
      id: '/examenes/$slug/'
      path: '/examenes/$slug'
      fullPath: '/examenes/$slug/'
      preLoaderRoute: typeof ExamenesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulacros/': {
      id: '/_authenticated/simulacros/'
      path: '/simulacros'
      fullPath: '/simulacros/'
      preLoaderRoute: typeof AuthenticatedSimulacrosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/temas/$slug/$subtopic': {
      id: '/temas/$slug/$subtopic'
      path: '/temas/$slug/$subtopic'
      fullPath: '/temas/$slug/$subtopic'
      preLoaderRoute: typeof TemasSlugSubtopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examenes/$slug/simulacro': {
      id: '/examenes/$slug/simulacro'
      path: '/examenes/$slug/simulacro'
      fullPath: '/examenes/$slug/simulacro'
      preLoaderRoute: typeof ExamenesSlugSimulacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/examen/$id': {
      id: '/_authenticated/examen/$id'
      path: '/examen/$id'
      fullPath: '/examen/$id'
      preLoaderRoute: typeof AuthenticatedExamenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examen-sesion/$sessionId': {
      id: '/_authenticated/examen-sesion/$sessionId'
      path: '/examen-sesion/$sessionId'
      fullPath: '/examen-sesion/$sessionId'
      preLoaderRoute: typeof AuthenticatedExamenSesionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/materias': {
      id: '/_authenticated/admin/materias'
      path: '/materias'
      fullPath: '/admin/materias'
      preLoaderRoute: typeof AuthenticatedAdminMateriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/examen-sesion/$sessionId/': {
      id: '/_authenticated/examen-sesion/$sessionId/'
      path: '/'
      fullPath: '/examen-sesion/$sessionId/'
      preLoaderRoute: typeof AuthenticatedExamenSesionSessionIdIndexRouteImport
      parentRoute: typeof AuthenticatedExamenSesionSessionIdRoute
    }
    '/_authenticated/admin/examenes/': {
      id: '/_authenticated/admin/examenes/'
      path: '/examenes'
      fullPath: '/admin/examenes/'
      preLoaderRoute: typeof AuthenticatedAdminExamenesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ejercicios/': {
      id: '/_authenticated/admin/ejercicios/'
      path: '/ejercicios'
      fullPath: '/admin/ejercicios/'
      preLoaderRoute: typeof AuthenticatedAdminEjerciciosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/examen-sesion/$sessionId/resultado': {
      id: '/_authenticated/examen-sesion/$sessionId/resultado'
      path: '/resultado'
      fullPath: '/examen-sesion/$sessionId/resultado'
      preLoaderRoute: typeof AuthenticatedExamenSesionSessionIdResultadoRouteImport
      parentRoute: typeof AuthenticatedExamenSesionSessionIdRoute
    }
    '/_authenticated/admin/examenes/nuevo': {
      id: '/_authenticated/admin/examenes/nuevo'
      path: '/examenes/nuevo'
      fullPath: '/admin/examenes/nuevo'
      preLoaderRoute: typeof AuthenticatedAdminExamenesNuevoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/examenes/$id': {
      id: '/_authenticated/admin/examenes/$id'
      path: '/examenes/$id'
      fullPath: '/admin/examenes/$id'
      preLoaderRoute: typeof AuthenticatedAdminExamenesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ejercicios/nuevo': {
      id: '/_authenticated/admin/ejercicios/nuevo'
      path: '/ejercicios/nuevo'
      fullPath: '/admin/ejercicios/nuevo'
      preLoaderRoute: typeof AuthenticatedAdminEjerciciosNuevoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ejercicios/$id': {
      id: '/_authenticated/admin/ejercicios/$id'
      path: '/ejercicios/$id'
      fullPath: '/admin/ejercicios/$id'
      preLoaderRoute: typeof AuthenticatedAdminEjerciciosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminMateriasRoute: typeof AuthenticatedAdminMateriasRoute
  AuthenticatedAdminEjerciciosIdRoute: typeof AuthenticatedAdminEjerciciosIdRoute
  AuthenticatedAdminEjerciciosNuevoRoute: typeof AuthenticatedAdminEjerciciosNuevoRoute
  AuthenticatedAdminExamenesIdRoute: typeof AuthenticatedAdminExamenesIdRoute
  AuthenticatedAdminExamenesNuevoRoute: typeof AuthenticatedAdminExamenesNuevoRoute
  AuthenticatedAdminEjerciciosIndexRoute: typeof AuthenticatedAdminEjerciciosIndexRoute
  AuthenticatedAdminExamenesIndexRoute: typeof AuthenticatedAdminExamenesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminMateriasRoute: AuthenticatedAdminMateriasRoute,
    AuthenticatedAdminEjerciciosIdRoute: AuthenticatedAdminEjerciciosIdRoute,
    AuthenticatedAdminEjerciciosNuevoRoute:
      AuthenticatedAdminEjerciciosNuevoRoute,
    AuthenticatedAdminExamenesIdRoute: AuthenticatedAdminExamenesIdRoute,
    AuthenticatedAdminExamenesNuevoRoute: AuthenticatedAdminExamenesNuevoRoute,
    AuthenticatedAdminEjerciciosIndexRoute:
      AuthenticatedAdminEjerciciosIndexRoute,
    AuthenticatedAdminExamenesIndexRoute: AuthenticatedAdminExamenesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedExamenSesionSessionIdRouteChildren {
  AuthenticatedExamenSesionSessionIdResultadoRoute: typeof AuthenticatedExamenSesionSessionIdResultadoRoute
  AuthenticatedExamenSesionSessionIdIndexRoute: typeof AuthenticatedExamenSesionSessionIdIndexRoute
}

const AuthenticatedExamenSesionSessionIdRouteChildren: AuthenticatedExamenSesionSessionIdRouteChildren =
  {
    AuthenticatedExamenSesionSessionIdResultadoRoute:
      AuthenticatedExamenSesionSessionIdResultadoRoute,
    AuthenticatedExamenSesionSessionIdIndexRoute:
      AuthenticatedExamenSesionSessionIdIndexRoute,
  }

const AuthenticatedExamenSesionSessionIdRouteWithChildren =
  AuthenticatedExamenSesionSessionIdRoute._addFileChildren(
    AuthenticatedExamenSesionSessionIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedExamenSesionSessionIdRoute: typeof AuthenticatedExamenSesionSessionIdRouteWithChildren
  AuthenticatedExamenIdRoute: typeof AuthenticatedExamenIdRoute
  AuthenticatedSimulacrosIndexRoute: typeof AuthenticatedSimulacrosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedExamenSesionSessionIdRoute:
    AuthenticatedExamenSesionSessionIdRouteWithChildren,
  AuthenticatedExamenIdRoute: AuthenticatedExamenIdRoute,
  AuthenticatedSimulacrosIndexRoute: AuthenticatedSimulacrosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  ExamenesOficialesRoute: ExamenesOficialesRoute,
  EjercicioIdRoute: EjercicioIdRoute,
  ExamenesIndexRoute: ExamenesIndexRoute,
  TemasIndexRoute: TemasIndexRoute,
  ExamenesSlugSimulacroRoute: ExamenesSlugSimulacroRoute,
  TemasSlugSubtopicRoute: TemasSlugSubtopicRoute,
  ExamenesSlugIndexRoute: ExamenesSlugIndexRoute,
  TemasSlugIndexRoute: TemasSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
